export default function Head() {
  return (
    <>
      <title>ChatGPT Messenger</title>
      <meta name="description" content="Generated by Next.js" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
